apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: securitygroup-for-pod
  region: ap-northeast-2
  version: "1.26"

vpc:
  cidr: "10.0.0.0/16"

managedNodeGroups:
- name: spot
  spot: true
  instanceTypes: ["m5.large", "c5.large", "c5d.large"]
  minSize: 2
  maxSize: 2
  desiredCapacity: 2
  volumeSize: 10
  privateNetworking: true
